/**
 * home-iot-api
 * Joel's API for the EatBacon IOT project
 *
 * OpenAPI spec version: 1.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { City } from './city';
import { Forecast } from './forecast';

export interface ForecastResponse { 
    city?: City;
    values?: Array<Forecast>;
}