/**
 * home-iot-api
 * Joel's API for the EatBacon IOT project
 *
 * OpenAPI spec version: 1.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 * a single temperature zone
 */
export interface TemperatureZone { 
    /**
     * the unique identifier for the zone
     */
    id: number;
    name: string;
    inputPosition?: number;
    outputPosition?: number;
    zone?: string;
}