/**
 * home-iot-api
 * Joel's API for the EatBacon IOT project
 *
 * OpenAPI spec version: 1.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 * status of a single zone
 */
export interface TemperatueZoneStatus { 
    /**
     * the unique identifier for the zone
     */
    id: string;
    /**
     * the name of the zone
     */
    name?: string;
    /**
     * the temperature in the zone
     */
    value: number;
    /**
     * the temperature units
     */
    units?: TemperatueZoneStatus.UnitsEnum;
    /**
     * the timestamp when the temperature was measured
     */
    timestamp: Date;
}
export namespace TemperatueZoneStatus {
    export type UnitsEnum = 'celsius' | 'fahrenheit';
    export const UnitsEnum = {
        Celsius: 'celsius' as UnitsEnum,
        Fahrenheit: 'fahrenheit' as UnitsEnum
    };
}